name: Auto Update Packages
on:
  schedule:
    - cron: '0 5 * * *' # Run at 05:00 UTC every day
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - '*/update.ps1' # Run when update scripts are modified

jobs:
  update_packages:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Chocolatey-AU
        run: Install-Module Chocolatey-AU -Force -AcceptLicense

      - name: Run Update Script for my-awesome-app
        run: ./update.ps1
        working-directory: ./my-awesome-app
        # Add more steps here for other applications as you add them

      - name: Pack and Push to MyGet
        run: |
          # Loop through all created nupkg files and push them
          Get-ChildItem -Path ./ -Recurse -Filter "*.nupkg" | ForEach-Object {
            choco push $_.FullName --source "https://www.myget.org/F/goodlight-desktop-repo/api/v2/package" --api-key ${{ secrets.MYGET_API_KEY }} --force
          }
        # Note: Replace 'my-gui-feed' with your actual MyGet feed name in the URL above.
